server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://121.89.232.214:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#seata:
#  config:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848
#      group: "SEATA_GROUP"
#      namespace: ""
#      dataId: "seataServer.properties"
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: "SEATA_GROUP"
#      namespace: ""
#      username: "nacos"
#      password: "nacos"
#  tx-service-group: default_tx_group #自定义事务组名称需要与seata-server中的对应
#    nacos:
#      discovery:
#        server-addr: localhost:8848

seata:
  application-id: seata-server
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      application: seata-server # seata 服务名
      # 非本地请修改具体的地址
      server-addr: http://127.0.0.1:8848
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      # nacos ip地址
      server-addr: http://127.0.0.1:8848
      group: SEATA_GROUP
      data-id: "seataServer.properties"


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml