server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 121.89.232.214:2111 #配置Nacos地址

#端口暴漏
management:
  endpoints:
    web:
      exposure:
        include: '*'